"""initial schema

Revision ID: 7970b10ad246
Revises: 
Create Date: 2026-06-12 15:07:06.149227

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7970b10ad246'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    # FIX: removed duplicate entry; added postgresql_using for TEXT→JSON cast
    op.alter_column('ai_predictions', 'input_features',
               existing_type=sa.TEXT(),
               type_=sa.JSON(),
               existing_nullable=True,
               postgresql_using='input_features::json')

    # FIX: added postgresql_using for output_result TEXT→JSON cast
    op.alter_column('ai_predictions', 'output_result',
               existing_type=sa.TEXT(),
               type_=sa.JSON(),
               existing_nullable=True,
               postgresql_using='output_result::json')

    op.create_index(op.f('ix_ai_predictions_id'), 'ai_predictions', ['id'], unique=False)
    op.drop_constraint(op.f('ai_predictions_customer_id_fkey'), 'ai_predictions', type_='foreignkey')
    op.create_foreign_key(None, 'ai_predictions', 'customers', ['customer_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_attendance_id'), 'attendance', ['id'], unique=False)
    op.drop_constraint(op.f('attendance_session_id_fkey'), 'attendance', type_='foreignkey')
    op.create_foreign_key(None, 'attendance', 'health_sessions', ['session_id'], ['id'], ondelete='CASCADE')
    op.add_column('customers', sa.Column('total_debt', sa.Float(), nullable=True))
    op.create_index(op.f('ix_customers_id'), 'customers', ['id'], unique=False)
    op.create_index(op.f('ix_customers_phone'), 'customers', ['phone'], unique=False)
    op.create_index(op.f('ix_customers_region'), 'customers', ['region'], unique=False)
    op.create_index(op.f('ix_customers_risk_level'), 'customers', ['risk_level'], unique=False)
    op.create_index(op.f('ix_customers_status'), 'customers', ['status'], unique=False)
    op.create_index(op.f('ix_distributions_id'), 'distributions', ['id'], unique=False)
    op.create_index(op.f('ix_distributions_region'), 'distributions', ['region'], unique=False)
    op.create_index(op.f('ix_health_sessions_id'), 'health_sessions', ['id'], unique=False)
    op.create_index(op.f('ix_health_sessions_region'), 'health_sessions', ['region'], unique=False)
    op.add_column('payments', sa.Column('payment_method', sa.String(length=50), nullable=True))
    op.add_column('payments', sa.Column('transaction_ref', sa.String(length=100), nullable=True))
    op.add_column('payments', sa.Column('recorded_by', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_payments_customer_id'), 'payments', ['customer_id'], unique=False)
    op.create_index(op.f('ix_payments_due_date'), 'payments', ['due_date'], unique=False)
    op.create_index(op.f('ix_payments_id'), 'payments', ['id'], unique=False)
    op.create_index(op.f('ix_payments_status'), 'payments', ['status'], unique=False)
    op.drop_constraint(op.f('payments_customer_id_fkey'), 'payments', type_='foreignkey')
    op.create_foreign_key(None, 'payments', 'customers', ['customer_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'payments', 'users', ['recorded_by'], ['id'])
    op.add_column('products', sa.Column('low_stock_alert', sa.Integer(), nullable=True))
    op.add_column('products', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.create_index(op.f('ix_products_id'), 'products', ['id'], unique=False)
    op.create_index(op.f('ix_reports_id'), 'reports', ['id'], unique=False)
    op.create_index(op.f('ix_uploaded_files_id'), 'uploaded_files', ['id'], unique=False)
    op.add_column('users', sa.Column('last_login', sa.DateTime(timezone=True), nullable=True))
    op.drop_constraint(op.f('users_email_key'), 'users', type_='unique')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_unique_constraint(op.f('users_email_key'), 'users', ['email'], postgresql_nulls_not_distinct=False)
    op.drop_column('users', 'last_login')
    op.drop_index(op.f('ix_uploaded_files_id'), table_name='uploaded_files')
    op.drop_index(op.f('ix_reports_id'), table_name='reports')
    op.drop_index(op.f('ix_products_id'), table_name='products')
    op.drop_column('products', 'is_active')
    op.drop_column('products', 'low_stock_alert')
    op.drop_constraint(None, 'payments', type_='foreignkey')
    op.drop_constraint(None, 'payments', type_='foreignkey')
    op.create_foreign_key(op.f('payments_customer_id_fkey'), 'payments', 'customers', ['customer_id'], ['id'])
    op.drop_index(op.f('ix_payments_status'), table_name='payments')
    op.drop_index(op.f('ix_payments_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_due_date'), table_name='payments')
    op.drop_index(op.f('ix_payments_customer_id'), table_name='payments')
    op.drop_column('payments', 'recorded_by')
    op.drop_column('payments', 'transaction_ref')
    op.drop_column('payments', 'payment_method')
    op.drop_index(op.f('ix_health_sessions_region'), table_name='health_sessions')
    op.drop_index(op.f('ix_health_sessions_id'), table_name='health_sessions')
    op.drop_index(op.f('ix_distributions_region'), table_name='distributions')
    op.drop_index(op.f('ix_distributions_id'), table_name='distributions')
    op.drop_index(op.f('ix_customers_status'), table_name='customers')
    op.drop_index(op.f('ix_customers_risk_level'), table_name='customers')
    op.drop_index(op.f('ix_customers_region'), table_name='customers')
    op.drop_index(op.f('ix_customers_phone'), table_name='customers')
    op.drop_index(op.f('ix_customers_id'), table_name='customers')
    op.drop_column('customers', 'total_debt')
    op.drop_constraint(None, 'attendance', type_='foreignkey')
    op.create_foreign_key(op.f('attendance_session_id_fkey'), 'attendance', 'health_sessions', ['session_id'], ['id'])
    op.drop_index(op.f('ix_attendance_id'), table_name='attendance')
    op.drop_constraint(None, 'ai_predictions', type_='foreignkey')
    op.create_foreign_key(op.f('ai_predictions_customer_id_fkey'), 'ai_predictions', 'customers', ['customer_id'], ['id'])
    op.drop_index(op.f('ix_ai_predictions_id'), table_name='ai_predictions')
    op.alter_column('ai_predictions', 'output_result',
               existing_type=sa.JSON(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('ai_predictions', 'input_features',
               existing_type=sa.JSON(),
               type_=sa.TEXT(),
               existing_nullable=True)
    # ### end Alembic commands ###